# Interpolation methods
INTERPOLATION_DIRECT = 0
INTERPOLATION_INCREMENTAL = 1

# Parameters for sliding window interpolation (INTERPOLATION_INCREMENTAL)
INTERPOLATION_TILE = 1000
INTERPOLATION_PADDING = 100

# LAS Classification Codes
UNASSIGNED = 1
GROUND = 2
LOW_VEGETATION = 3
MED_VEGETATION = 4
HIGH_VEGETATION = 5
BUILDING = 6
WATER = 9
