# Interpolation methods
INTERPOLATION_DIRECT = 0
INTERPOLATION_INCREMENTAL = 1

# Parameters for sliding window interpolation (INTERPOLATION_INCREMENTAL)
INTERPOLATION_TILE = 1000
INTERPOLATION_PADDING = 100